version: '3.4'
services:
  #Backend del TUTV
  #tutv:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: backend_tutv
  #  environment:
  #    - REST_SERV_PORT=3000
  #    - DB_TYPE=mariadb
  #    - DB_USER=root
  #    - DB_PASS=1234
  #    - DB_HOST=127.0.0.1
  #    - DB_PORT=3306
  #    - DB_BBDD=TUTV
  #  depends_on: 
  #    - mariadb
  #Servicdor de base de datos
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - '${PWD}/mariadb:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_USER=TUTV
      - MARIADB_PASSWORD=1234
      - MARIADB_DATABASE=TUTV

volumes:
  mariadb_data:
    driver: local